// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrq-Zz8LeTaORo9lR-Vf7oNvYxNxt8Z4k',
    appId: '1:51772174380:web:64adc3dba30a537826a189',
    messagingSenderId: '51772174380',
    projectId: 'appchat2-f04d6',
    authDomain: 'appchat2-f04d6.firebaseapp.com',
    storageBucket: 'appchat2-f04d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWPgYoaZR-I3yJ1Ghz8XA7GugeQyxhXs',
    appId: '1:51772174380:android:34eb4701f329fdc526a189',
    messagingSenderId: '51772174380',
    projectId: 'appchat2-f04d6',
    storageBucket: 'appchat2-f04d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuSevHaZ9TwC7hc4I_Hhxij_jvlZI22TQ',
    appId: '1:51772174380:ios:ce11f7b28271b6a826a189',
    messagingSenderId: '51772174380',
    projectId: 'appchat2-f04d6',
    storageBucket: 'appchat2-f04d6.appspot.com',
    iosBundleId: 'com.example.tigerAppChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuSevHaZ9TwC7hc4I_Hhxij_jvlZI22TQ',
    appId: '1:51772174380:ios:0c3eebf6eec2086326a189',
    messagingSenderId: '51772174380',
    projectId: 'appchat2-f04d6',
    storageBucket: 'appchat2-f04d6.appspot.com',
    iosBundleId: 'com.example.tigerAppChat.RunnerTests',
  );
}
